### ISSUE TITLE
Creating additional columns

### ISSUE THREAD

**Issue by Ph0non** [Ph0non/NuclideVector#4]
https://github.com/barche/QML.jl/issues/30

**Comment by barche** [comment]
OK, I think the problem is that you replace the entire model, so you should connect to view's onModelChanged signal. See the attached diff for the changes I had to make. I couldn't get the computation itself running, so this uses random data. While the main change is in the QML, you can also get away with not using global on the listModel now I think, unless it's needed elsewhere. Nice looking GUI, BTW :)
The diff: [addcolumns.txt](https://github.com/Ph0non/NuclideVector/files/737802/addcolumns.txt)

**Comment by Ph0non** [comment]
fixed with d1070160d60ab3e708487a65d80d48e3611fd38d
